// Ye component paperData (meta + questions) ko ek asli exam-paper
// jaisi shakal mein dikhata hai (print ke waqt bhi yehi hissa dikhega)
export default function PaperPreview({ data }) {
  const { meta, questions } = data;

  return (
    <div id="paper-preview" className="border border-gray-200 rounded-xl p-6 font-serif animate-fadeIn">
      <div className="text-center border-b-2 border-gray-800 pb-3 mb-4">
        <h2 className="text-xl font-bold">{meta.schoolName}</h2>
        <p className="text-sm text-gray-500 mt-1">
          {meta.examName} &nbsp;|&nbsp; Class: {meta.className} &nbsp;|&nbsp; Subject: {meta.subject}
        </p>
      </div>

      <div className="flex flex-wrap justify-between gap-2 text-sm mb-4">
        <span><b>Teacher:</b> {meta.teacherName}</span>
        <span><b>Date:</b> {meta.examDate}</span>
        <span><b>Time:</b> {meta.timeAllowed}</span>
        <span><b>Total Marks:</b> {meta.totalMarks}</span>
      </div>

      <div className="bg-bgsoft border-l-4 border-primary px-3 py-2 text-sm mb-5">
        <b>Instructions:</b> {meta.instructions}
        <br />
        <span className="text-xs text-gray-400">(Difficulty level: {meta.difficulty})</span>
      </div>

      <div className="space-y-4">
        {questions.map((q) => (
          <div key={q.number} className="text-sm leading-relaxed">
            <span className="font-bold mr-1">Q{q.number}.</span>
            {q.text}
            <span className="float-right text-xs text-gray-400">[{q.marks} marks]</span>

            {q.options && (
              <div className="pl-5 mt-1.5 text-sm">
                {q.options.map((opt, i) => (
                  <div key={i}>{String.fromCharCode(65 + i)}) {opt}</div>
                ))}
              </div>
            )}
          </div>
        ))}
      </div>

      <div className="mt-6 border-t border-dashed border-gray-300 pt-2 text-xs text-gray-400 text-center">
        Generated by AI Paper Generator — Demo Version
      </div>
    </div>
  );
}
